- name: docker build and push
  hosts: 127.0.0.1# Replace with the hostname or IP address of your target server
  connection:local
  become: yes  # Run tasks with sudo privileges

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes   

    - name: Build Docker Image
      command: docker build -t petstore .
      args:
        chdir: /var/lib/jenkins/workspace/petstore

    - name: tag image
      command: docker tag petstore:latest abhi/petstore:latest 

    - name: Log in to Docker Hub
      community.docker.docker_login:
        registry_url: https://index.docker.io/v1/
        username: abhi38366
        password: dckr_pat_czMqvRdqX8NyFbkkTT_5AyWaNms

    - name: Push image
      command: docker push abhi/petstore:latest

    - name: Run container
      command: docker run -d --name pet1 -p 8081:8080 abhi/petstore:latest
